-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXIST Customer CASCADE;
DROP TABLE IF EXIST Receiver CASCADE;
DROP TABLE IF EXIST Worker CASCADE;
DROP TABLE IF EXIST Unit CASCADE;
DROP TABLE IF EXIST Waybill CASCADE;
DROP TABLE IF EXIST Car CASCADE;
DROP TABLE IF EXIST Transport CASCADE;