-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Receiver CASCADE;
DROP TABLE IF EXISTS Worker CASCADE;
DROP TABLE IF EXISTS Unit CASCADE;
DROP TABLE IF EXISTS Waybill CASCADE;
DROP TABLE IF EXISTS Car CASCADE;
DROP TABLE IF EXISTS Transport CASCADE;